os: linux
language: python
sudo: required
services:
  - docker
env:
  global:
    - CONAN_UPLOAD: "https://api.bintray.com/conan/osechet/Conan"
    - CONAN_REFERENCE: "Qt/5.6.2"
    - CONAN_USERNAME: "osechet"
    - CONAN_CHANNEL: "stable"
    - CONAN_TOTAL_PAGES: 2
  matrix:
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1

    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1

matrix:
   include:
       - os: osx
         osx_image: xcode8.2
         language: generic
         env: CONAN_CURRENT_PAGE=1

       - os: osx
         osx_image: xcode7.3
         language: generic
         env: CONAN_CURRENT_PAGE=1

       - os: osx
         osx_image: xcode6.4
         language: generic
         env: CONAN_CURRENT_PAGE=1

cache: pip

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

before_script:
  - chmod +x .travis/before_script.sh
  - ./.travis/before_script.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
