build: false
environment:
    MINGW_CONFIGURATIONS: "4.8@x86_64@seh@posix, 4.9@x86_64@seh@posix, 6.2@x86_64@seh@posix"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "Qt/5.6.2"
    CONAN_USERNAME: "osechet"
    CONAN_CHANNEL: "stable"
    CONAN_TOTAL_PAGES: 16
    CONAN_VISUAL_VERSIONS: "12,14"

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4
        - CONAN_CURRENT_PAGE: 5
        - CONAN_CURRENT_PAGE: 6
        - CONAN_CURRENT_PAGE: 7
        - CONAN_CURRENT_PAGE: 8
        - CONAN_CURRENT_PAGE: 9
        - CONAN_CURRENT_PAGE: 10
        - CONAN_CURRENT_PAGE: 11
        - CONAN_CURRENT_PAGE: 12
        - CONAN_CURRENT_PAGE: 13
        - CONAN_CURRENT_PAGE: 14
        - CONAN_CURRENT_PAGE: 15
        - CONAN_CURRENT_PAGE: 16

install:
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory

test_script:
  - python build.py
